version: '3.8'
###################################################################################
services:
###################################################################################
  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    command: ["sh", "/app/start.sh"]
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    restart: always
###################################################################################
  users-management:
    build:
      context: ./services/users-management
    container_name: users-management
    command: ["sh", "/app/start.sh"]
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    restart: always
###################################################################################
  supplier-service:
    build:
      context: ./services/supplier-service
    container_name: supplier-service
    command: ["sh", "/app/start.sh"]
    ports:
      - "3002:3002"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    restart: always
###################################################################################
  product-order-service:
    build:
      context: ./services/product-order-service
    container_name: product-order-service
    command: ["sh", "/app/start.sh"]
    ports:
      - "3003:3003"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    restart: always
###################################################################################
  notification-service:
    build:
      context: ./services/notification-service
    container_name: notification-service
    command: ["npm", "start"]
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: always
###################################################################################
  file-service:
    build:
      context: ./services/file-service
    container_name: file-service
    command: ["sh", "/app/start.sh"]
    ports:
      - "4005:4005"
    depends_on:
      - mysql
    env_file:
      - .env
    restart: always
###################################################################################
###################################################################################
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
###################################################################################
###################################################################################
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis-data:/data
    restart: always
###################################################################################
###################################################################################
volumes:
  mysql-data:
  redis-data: